### PR TITLE
feat: add avatar visibility option

### PR DESCRIPTION
**Pull request by BerniWittmann**
Gives users the option to hide or show the avatar

### CODE REVIEW

**Comment by BerniWittmann** [comment]
@antonreshetov #16 was a new template and you answered, that you want to implement it as an option for all templates. This is also stated in the [Github Project Card](https://github.com/antonreshetov/mysigmail/projects/1#card-16199931). 

So i came up with this PR, which adds an option to hide the avatar

**Comment by antonreshetov** [comment]
@BerniWittmann 
I mean, I'm going to implement it. What I actually doing, I have locally there is a branch and the rough work on this.

Well, not to lose your work. Let's make some adjustments

Avatar is enabled by default. Accordingly, the Avatar Visibility option must have the switch already enabled.

Rename Avatar Visibility => Avatar and remove labels from the switch

**Comment by antonreshetov** [comment]
You need to be sensitive to someone else's work, so I just adjusted yours. :)

**Comment by antonreshetov** [comment]
@BerniWittmann please adjust the PR so I can merge it

**Pull request merged**
